spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/wlioe/spring--clould.git
          search-paths: spring-cloud-config
          username: wlioe
          password: wang199979@

server:
  port: 8888
